In [1]:
import numpy as np

In [21]:
marks = np.array([
    [70, 80, 90],   # Student 1
    [60, 75, 85],   # Student 2
    [88, 92, 95]    # Student 3
])


In [22]:
marks

array([[70, 80, 90],
       [60, 75, 85],
       [88, 92, 95]])

# Get marks of Student 2

In [23]:
marks[1]


array([60, 75, 85])

# Get Math marks of all students (column 0)

In [24]:
marks[:, 0]


array([70, 60, 88])

# Get top 2 students, last 2 subjects

In [25]:
marks[:2, 1:]


array([[80, 90],
       [75, 85]])