In [1]:
import numpy as np

In [4]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [10]:
a[1:4]      # [20 30 40]

array([20, 30, 40])

In [11]:
a[:3]       # [10 20 30]

array([10, 20, 30])

In [12]:
a[::2]      # [10 30 50]

array([10, 30, 50])

# Analogy:
Like cutting cake 🎂 — start slice, end slice, step slices.