In [15]:
import numpy as np

In [16]:
a = np.array([1, 4, 9, 16, 25])

In [21]:
np.log(a)      # natural log



array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582])

In [22]:
np.log10(a)    # base 10


array([0.        , 0.60205999, 0.95424251, 1.20411998, 1.39794001])

In [23]:
np.exp(a)      # e^x

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10])

## 📌 Used in:

* Feature scaling

* Probability

* Loss functions