In [4]:
import numpy as np

In [8]:
data = np.array([
    [65, 70, 80],
    [90, 85, 88],
    [40, 55, 60]
])


In [11]:
data

array([[65, 70, 80],
       [90, 85, 88],
       [40, 55, 60]])

# All values > 70

In [9]:
data[data > 70]


array([80, 90, 85, 88])

# Students with any subject < 50

In [10]:
data[data < 50]


array([40])