In [4]:
import numpy as np

In [5]:
marks = np.array([45, 60, 72, 88, 35, 90])

passed = marks[marks >= 50]
print(passed)


[60 72 88 90]


# AND Condition

In [6]:
marks[(marks >= 50) & (marks < 80)]


array([60, 72])

# OR Condition

In [7]:
marks[(marks < 40) | (marks > 85)]


array([88, 35, 90])

# ⚠️ IMPORTANT:

* Use & and |

* NOT and, or

# 🧠 Memory trick:

> NumPy thinks in bitwise, not English.