In [1]:
import numpy as np

In [13]:
b = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [14]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

# Access Single Element

In [17]:
b[0, 1]   # 20
b[2, 2]   # 90

np.int64(90)

# Access Whole Row

In [18]:
b[1]      # [40 50 60]

array([40, 50, 60])

# Access whole Column


In [19]:
b[:, 1]   # [20 50 80]


array([20, 50, 80])

# Important rule

*   First → rows

*   Second → columns