In [2]:
import numpy as np

# Zeros

In [7]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

# Ones

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

# Range

In [9]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Use case:

### Initialize model weights

### Create index data

### Dummy datasets