In [15]:
import numpy as np

In [16]:
a = np.array([1, 4, 9, 16, 25])

# Square Root

In [17]:
np.sqrt(a)


array([1., 2., 3., 4., 5.])

# Power

In [18]:
np.power(a, 2)


array([  1,  16,  81, 256, 625])

# Absolute

In [19]:
np.abs([-10, 5, -3])


array([10,  5,  3])